CFLAGS=-g -O3 -Wall -std=c99   -fopenmp -lm

all: boucle-for-1 boucle-for-2 sum


film: film.c
	gcc film.c -g -O3 -Wall -std=c99   -fopenmp  -mcmodel=large

clean:
	-rm -rf *.o *SYM boucle-for-1 boucle-for-2 sum film